apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-dev
spec:
  replicas: 2
    spec:
      containers:
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
