apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx-dev
  template:
    metadata:
      labels:
        app: my-nginx-dev
    spec:
      containers:
      - name: nginx
        image: alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
