apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
resources: 
  - ../../base/deployment.yaml
  - ../../base/service.yaml

namePrefix: dev-

images:
  - name: nginx
    newTag: alpine

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: my-app 
